version: '3.2'
services:
    main:
        image: kimsufi-watcher
        build:
            context: .
            dockerfile: ./docker/python3/Dockerfile
        command: /env/bin/python main.py
        environment:
          CHAT_ID: ${CHAT_ID}
          API_TOKEN: ${API_TOKEN}
